// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type User struct {
	ID               string     `json:"id"`
	Reputation       *string    `json:"reputation"`
	CreationDate     *time.Time `json:"creationDate"`
	DisplayName      *string    `json:"displayName"`
	LastAccessDate   *time.Time `json:"lastAccessDate"`
	Views            *int       `json:"views"`
	WebsiteURL       *string    `json:"websiteUrl"`
	Location         *string    `json:"location"`
	AboutMe          *string    `json:"aboutMe"`
	Age              *int       `json:"age"`
	UpVotes          *int       `json:"upVotes"`
	DownVotes        *int       `json:"downVotes"`
	EmailHash        *string    `json:"emailHash"`
	AccountID        *int       `json:"accountId"`
	LastAccessedDate *time.Time `json:"lastAccessedDate"`
	ProfileImageURL  *string    `json:"profileImageUrl"`
}
